apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DATABASE_PASSWORD: YWtoaWwxMjM=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmFraGlsMTIzQHBvc3RncmVzLmM1bWNzMHFvMG1jdS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==

